CREATE SCHEMA IF NOT EXISTS energy;
CREATE SCHEMA IF NOT EXISTS mcs;

CREATE TABLE energy.dim_time (
  time_id           SERIAL PRIMARY KEY,
  consumption_date  DATE        NOT NULL UNIQUE,
  year              INTEGER     NOT NULL,
  quarter           SMALLINT    NOT NULL,
  month             SMALLINT    NOT NULL,
  day               SMALLINT    NOT NULL,
  weekday           SMALLINT    NOT NULL,
  is_weekend        BOOLEAN     NOT NULL,
  season            VARCHAR(10),         
  is_school_term    BOOLEAN,             
  is_holiday        BOOLEAN
);

CREATE TABLE energy.fact_energy (
  fact_id           SERIAL PRIMARY KEY,
  time_id           INTEGER    NOT NULL REFERENCES energy.dim_time(time_id),
  consumption_hour  SMALLINT   NOT NULL,
  consumption_mwh   NUMERIC   NOT NULL,
  price             NUMERIC    NOT NULL,
  cost              NUMERIC    NOT NULL 
);

CREATE TABLE mcs.config_date (
  year           INTEGER PRIMARY KEY,
  start_date     DATE NOT NULL,
  end_date  	 DATE NOT NULL
);


CREATE TABLE mcs.holiday_dates (
  id            INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  year          INTEGER       NOT NULL,
  holiday_date  DATE          NOT NULL,
  description   VARCHAR(100),

  CONSTRAINT fk_holiday_dates_year
    FOREIGN KEY (year)
    REFERENCES mcs.config_date (year)
);


TRUNCATE TABLE energy.fact_energy;


TRUNCATE TABLE energy.dim_time CASCADE;